### ISSUE TITLE
Eliminate aes() ?

### ISSUE THREAD

**Issue by kwstat** [thomasp85/pipeplotter#5]
I'm a very long-time user of trellis/lattice, and I've always found the ggplot2 syntax aes() to be awkward.  Almost all graphs need an "x" and a "y" and I think it would be a lot more "elegant" to have ggplot2(data, x=, y=) than the syntax ggplot2(data, aes(x, y)).  Maybe you could streamline the code by chopping out aes() as part of the pipelining?  Something like this:

``` r
ggplot(mtcars) %>% 
    add_point(x=mpg, y=cyl, colour = gear)
```

**Comment by thomasp85** [comment]
I can't see that happening. The use of `aes()` is integral to how ggplot2 works, in that it determines wether to map or set an aesthetic. Consider the two examples below - they are both valid ggplot2 calls, but have very different meaning:

``` r
ggplot(mtcars) +
    geom_point(aes(x=mpg, y=cyl, colour=gear))

ggplot(mtcars) +
    geom_point(aes(x=mpg, y=cyl), colour=gear)
```

In the first example colour is mapped to the data found in the gear column of the data using whatever colour scale is specified (the default here), in the second colour is set to the value in the global gear variable (and errors if no such exist). There are no scales involved in the latter and it is assumed that gear holds a valid colour value...

**Comment by kwstat** [comment]
The lattice package is able to handle both of your use cases with much less code because it doesn't need an aes() function:

```
gear="red"
library(lattice)
xyplot(cyl ~ mpg, mtcars, col=mtcars$gear)
xyplot(cyl ~ mpg, mtcars, col=gear)
```

You have the opportunity with the pipeplotter to create verbs that take care of the aes() mappings for the user without the user needing to explicitly add the aes() function. It would simplify code for the vast majority of users.

**Comment by thomasp85** [comment]
Except it don't - deciding where to look is only one thing. As I wrote the other thing is whether to map the variable to a scale and show legends etc. Lattice and ggplot2 has different semantics and while you might prefer lattice this does not mean that it is simply a matter of changing the input style of functions
